<?php 
    foreach ($this->messages as $message){
        ?>
        <div class="alert alert-info"><?php echo $message; ?></div>
        <?php
    }
?>
<div class="btmspace-50 center">
      <h3 class="btmspace-10">Naše radionice</h3>
    </div>
    <ul class="nospace clear services">
      <li class="one_third first"><a href="http://igraonica.ict/Radionice/index/tip/1">
        <figure><img src="<?php echo $this->baseUrl('images/gallery/01.png');?>" alt="Crtaonica">
          <figcaption>Crtaonica</figcaption>
        </figure>
        </a></li>
      <li class="one_third"><a href="http://igraonica.ict/Radionice/index/tip/2">
        <figure><img src="<?php echo $this->baseUrl('images/gallery/02.png');?>" alt="Maskaonica">
          <figcaption>Maskaonica</figcaption>
        </figure>
        </a></li>
      <li class="one_third"><a href="http://igraonica.ict/Radionice/index/tip/3">
        <figure><img src="<?php echo $this->baseUrl('images/gallery/03.png');?>" alt="Plesaonica">
          <figcaption>Plesaonica</figcaption>
        </figure>
        </a></li>
    </ul>
    <p class="center"><a class="btn inverse" href="<?php echo $this->baseUrl('Authentification\login'); ?>">Prijavi se!</a></p>