

              <li>
            <article>    
                
                <figure class="avatar"><img src="<?php echo $this->baseUrl('images/demo/60x60.png');?>" alt=""></figure>
                <address>
                By <?php echo $this->korisnik->email;?>
                </address>
                <time datetime="2045-04-06T08:15+00:00"><?php echo date('Y-m-d H:i:s',$this->datum);?></time>
              </header>
              <div class="comcont">
                <p>
        <?php echo $this->tekst; ?></p>
              </div>
            </article>
          </li>