
<div class='col-lg-8 col-md-8 col-sm-8 col-xs-8'><h3>Upravljanje radionicama<br/></h3></div>
<?php
    if(!empty($this->errors)){
        foreach ($this->errors as $error){
            ?>
<div class="alert alert-danger"><?php echo $error; ?></div>
<?php
        }
    }
?>
<?php
    if(!empty($this->success)){
        foreach ($this->success as $data){
            ?>
<div class="alert alert-success"><?php echo $data; ?></div>
<?php
        }
    }
?>

        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
            <?php echo "<a class='btn btn-primary' href='".$this->baseUrl('Administration/radionice/operation/checkDate')."'>Dodavanje</a>";?>
            <br/>
        </div>
<?php if($this->prikazi):?>
  
        <form action="<?php echo $this->baseUrl('Administration/radionice/operation/checkDate');?>" method="post">
            <br/><br/>
            <div class="row">
                <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
                    <div class="form-group">
                                <div >

                                    Početak: <input type='text' id='datepicker1' name="pocetak" value="<?php echo $this->pocetak; ?>"/>

                                </div>
                            </div>
                    </div>
                    <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
                        <div class="form-group">
                                    <div>

                                        Završetak: <input type='text'  id='datepicker2' name="zavrsetak" value="<?php echo $this->zavrsetak; ?>"/>

                                    </div>
                                </div>
                    </div>
            </div>
            <div class="row">
                <div class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>
                <input type="submit" value="Proveri raspored" class="btn btn-lg btn-block"/>
        </div>
            </div>
        </form>
        <div></div>
        <?php endif;?>
        <?php if(!empty($this->radionice)):?>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Naziv</th>
                <th>Opis</th>
                <th>Pocetak</th>
                <th>Zavrsetak</th>
                <th>Izmeni</th>
                <th>Obrisi</th>
            </tr>
         <?php print $this->partialLoop('_radionica_admin.phtml',$this->radionice); ?>
        </table>
                <?php endif;?>
        <br/><br/>
        <?php echo $this->form;?>