<?php echo "<a href='".$this->baseUrl('Administration/slike/operation/insert')."'>Dodavanje</a>";?>
        <?php if(!empty($this->slike)):?>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>Slika</th>
                <th>Radionica</th>
                <th>Izmeni</th>
                <th>Obrisi</th>
            </tr>
         <?php print $this->partialLoop('_slike_admin.phtml',$this->slike); ?>
        </table>
                <?php endif;?>
<?php if($this->show) echo $this->form;?>