<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<!-- BOOTSTRAP STYLES-->
    <link href="<?php echo $this->baseUrl('assets/css/bootstrap.css');?>" rel="stylesheet" />
     <!-- FONTAWESOME STYLES-->
    <link href="<?php echo $this->baseUrl('assets/css/font-awesome.css');?>" rel="stylesheet" />
        <!-- CUSTOM STYLES-->
    <link href="<?php echo $this->baseUrl('assets/css/custom.css');?>" rel="stylesheet" />
    
    <link href="<?php echo $this->baseUrl('assets/css/morris.css');?>" rel="stylesheet">
     <!-- GOOGLE FONTS-->
   <link href='<?php echo $this->baseUrl('http://fonts.googleapis.com/css?family=Open+Sans');?>' rel='stylesheet' type='text/css' />
   <?php echo $this->headScript();?>
</head>
<body>
     
           
          
    <div id="wrapper">
         <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="adjust-nav">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->baseUrl('Administration/index'); ?>">
                        <img src="<?php echo $this->baseUrl('images/demo/60x60.png');?>" />

                    </a>
                    
                </div>
              
                <span class="logout-spn" >
                  <a href="#" style="color:#fff;">LOGOUT</a>  

                </span>
            </div>
        </div>
        <div class="clear"></div>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                 <?php    
                 $links = array(
                     'Upravljanje radionicama'=>$this->baseUrl('Administration/radionice/operation/prikaz'),
                     'Upravljanje slikama'=>$this->baseUrl('Administration/slike/operation/prikaz'),
                     'Upravljanje terminima'=>$this->baseUrl('Administration/termini/operation/prikaz'),
                     'Odjava'=>$this->baseUrl('Authentification/logout'),
                     'Povratak na sajt'=>$this->baseUrl('Index')
                      );
                foreach ($links as $key=>$value){
                    echo "<li><a href='".$value."'>".$key."</a></li>";
                }
                 ?>

                    
                    
                </ul>
                            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-lg-12">
                    <h2>ADMIN DASHBOARD</h2>  
                     
                    <?php echo $this->layout()->content; ?>
                    </div>
                </div>              
                <!-- /. ROW  -->
                <hr />
                <div class="row">
                    
                       
                </div>
                </div>
                <!-- /. ROW  --> 
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <div class="footer">
        <div class="row">
            <div class="col-lg-12" >
                &copy;  2014 yourdomain.com | Design by: <a href="http://binarytheme.com" style="color:#fff;" target="_blank">www.binarytheme.com</a>
            </div>
        </div>
    </div>
          

    <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="assets/js/jquery-1.10.2.js"></script>
      <!-- BOOTSTRAP SCRIPTS -->
    <script src="assets/js/bootstrap.min.js"></script>
      <!-- CUSTOM SCRIPTS -->
    <script src="assets/js/custom.js"></script>
    
   
</body>
</html>
