<!DOCTYPE html>
<!--
Template Name: Merciano
Author: <a href="http://www.os-templates.com/">OS Templates</a>
Author URI: http://www.os-templates.com/
Licence: Free to use under our free template licence terms
Licence URI: http://www.os-templates.com/template-terms
-->
<html>
<head>
<link rel="icon" href="<?php echo $this->baseUrl('images/demo/60x60.png');?>">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="<?php echo $this->baseUrl('layout/styles/layout.css');?>" rel="stylesheet" type="text/css" media="all">
<?php print $this->headTitle(); ?>
<?php print $this->headLink(); ?>
<?php  print $this->headScript(); ?>
</head>
<body id="top">
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- Top Background Image Wrapper -->
<div class="bgded overlay" style="background-image:url('<?php echo $this->baseUrl('images/demo/backgrounds/01.png');?>');">
  <!-- ################################################################################################ -->
  <div class="wrapper">
    <div id="pageintro" class="hoc clear"> 
      <!-- ################################################################################################ -->
      <article>
        <h1 class="heading">Igraonica "Vitez Koja"</h1>
        <a class="btn" href="<?php echo $this->baseUrl('Radionice'); ?>">Rezerviši termin</a>
      </article>
    </div>
  </div>
  <!-- ################################################################################################ -->
  <div class="wrapper row1">
    <header id="header" class="hoc clear"> 
      <!-- ################################################################################################ -->
      <div id="logo" class="fl_left">
        <h1><a href="<?php echo $this->baseUrl('Index'); ?>">Igraonica Vitez Koja</a></h1>
      </div>
      <nav id="mainav" class="fl_right">
        
              <?php print $this->placeholder("menu"); ?>
      </nav>
      <!-- ################################################################################################ -->
    </header>
  </div>
  <!-- ################################################################################################ -->
</div>
<!-- End Top Background Image Wrapper -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">
  <main class="hoc container clear"> 
    <!-- main body -->
    <!-- ################################################################################################ -->
                <?php echo $this->layout()->content; ?>
<!--    <div class="btmspace-50 center">
      <h3 class="btmspace-10">Naše radionice</h3>
    </div>
    <ul class="nospace clear services">
      <li class="one_third first"><a href="#">
        <figure><img src="images/gallery/01.png" alt="">
          <figcaption>Crtaonica</figcaption>
        </figure>
        </a></li>
      <li class="one_third"><a href="#">
        <figure><img src="images/gallery/02.png" alt="">
          <figcaption>Maskaonica</figcaption>
        </figure>
        </a></li>
      <li class="one_third"><a href="#">
        <figure><img src="images/gallery/03.png" alt="">
          <figcaption>Plesaonica</figcaption>
        </figure>
        </a></li>
    </ul>
    <p class="center"><a class="btn inverse" href="#">Prijavi se!</a></p>-->
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper bgded overlay" style="background-image:url('<?php echo $this->baseUrl('images/demo/backgrounds/02.png');?>');">
  <div class="hoc container clear"> 
    <!-- ################################################################################################ -->
    <div class="testimonial clear">
      <div class="one_third">
        <blockquote>Ova igraonica je najbolja u kraju!</blockquote>
        <figure><img class="circle" src="<?php echo $this->baseUrl('images/demo/60x60.png');?>" alt="">
          <figcaption><strong>Pera Peric</strong><br>
            <em>Roditelj</em></figcaption>
        </figure>
      </div>
    </div>
    <p class="center"><a class="btn" href="<?php echo $this->baseUrl('User'); ?>">Ostavi svoj komentar</a></p>
    <!-- ################################################################################################ -->
  </div>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->

    

<div class="wrapper row3">
  <section class="hoc container clear"> 
    <!-- ################################################################################################ -->
    <div class="btmspace-50 center">
      <h3 class="btmspace-10">Radionice u najavi</h3>
    </div>
    <div class="latest">
      <article class="clear">
      	<div class="one_third">
          <h3 class="heading">Maskaonica za trogodisnjake</h3>
          <ul class="nospace meta">
            <li>
              <time datetime="2018-02-06">6<sup>th</sup> Feb 2018</time>
            </li>
            <li>by <a href="#">Admin</a></li>
          </ul>
          <p>Tog i tog datuma odrzace se nova maskaonica za trogodisnjake blblbl</p>
        </div>
      </article>
    </div>
    <!-- ################################################################################################ -->
    <div class="clear"></div>
  </section>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row4">
  <footer id="footer" class="hoc clear"> 
    <!-- ################################################################################################ -->
    <div class="one_half first">
      <h6 class="title">Kontakt</h6>
      <address class="btmspace-30">
      Trajka Grkovića 1<br>
      Kotež, Beograd<br>
      11210
      </address>
      <ul class="nospace">
        <li class="btmspace-10"><i class="fa fa-phone"></i> +381 (60) 100 100</li>
        <li><i class="fa fa-envelope-o"></i> info@igraonicavitezkoja.com</li>
      </ul>
    </div>
    <div class="one_half">
      <h6 class="title">Fringilla eu efficitur</h6>
      <article>
        <h2 class="nospace font-x1"><a href="#">Dictum dui quisque</a></h2>
        <time class="font-xs" datetime="2045-04-06">Friday, 6<sup>th</sup> April 2045</time>
        <p>Lacinia gravida accumsan proin tincidunt auctor pharetra mauris id luctus tellus morbi eu magna sit amet.</p>
      </article>
    </div>
    <!-- ################################################################################################ -->
  </footer>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row5">
  <div id="copyright" class="hoc clear"> 
    <!-- ################################################################################################ -->
    <p class="fl_left">Copyright &copy; 2016 - All Rights Reserved - <a href="#">Domain Name</a></p>
    <p class="fl_right">Template by <a target="_blank" href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
    <!-- ################################################################################################ -->
  </div>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>
<!-- JAVASCRIPTS -->
<script src="<?php echo $this->baseUrl('layout/scripts/jquery.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('layout/scripts/jquery.backtotop.js');?>"></script>
<script src="<?php echo $this->baseUrl('layout/scripts/jquery.mobilemenu.js');?>"></script>
<script src="<?php echo $this->baseUrl('http://maps.google.com/maps/api/js?sensor=false');?>"></script>
<script src="<?php echo $this->baseUrl('layout/scripts/gmaps.js');?>"></script>
</body>
</html>